index:
  name: local
  workspace: C:\\workspace\\scixtracer_project\\workspace
storage:
  name: local
  workspace: C:\\workspace\\scixtracer_project\\workspace
metadata:
  name: local
  workspace: C:\\workspace\\scixtracer_project\\workspace