index:
  name: local
  workspace: /Users/sprigent/Workspace/scixtracer_project/workspace
storage:
  name: local
  workspace: /Users/sprigent/Workspace/scixtracer_project/workspace
metadata:
  name: local
  workspace: /Users/sprigent/Workspace/scixtracer_project/workspace
runner:
  name: local